AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template creates a route in an existing route table to enable communication through a VPC peering connection (uksb-1tthgi812) (tag:private-apigw-cross-region-3)'

Parameters:

  PeerID:
    Description: Peering ID connection (Must have a prefix of "pcx-")
    Type: String
    
  REMOTEVPCCIDR:
    Description: Remote vpc CIDR Block (must be a /16 block)
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){2}0\.0\/16$
    ConstraintDescription: Must be a valid /16 IP CIDR range of the form x.x.0.0/16.

  RouteTableReference:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /myapp/routetableid
    Description: "DO NOT CHANGE THIS VALUE. It retrieves the RouteTableId from SSM Parameter Store."

Resources:
  myRoutePeering:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: RouteTableReference
      DestinationCidrBlock: !Ref REMOTEVPCCIDR
      VpcPeeringConnectionId: !Ref PeerID
